-- public.vagas definition

-- Drop table

-- DROP TABLE public.vagas;

CREATE TABLE public.vagas (
	nome varchar NULL,
	descricao varchar NULL,
	prazodata _date NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE public.empresas (
	id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome_empresa varchar NULL
);

CREATE TABLE public.requisitos (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar NULL,
	tempo_experiencia int4 NULL
);
