-- public.vagas definition

-- Drop table

-- DROP TABLE public.vagas;

CREATE TABLE public.vagas (
	nome varchar NULL,
	descricao varchar NULL,
	prazodata _date NULL,
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY
);